<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { RouterLink } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { useDecisionsStore } from '@/stores/decisions'
import { useDiscoveryStore } from '@/stores/discovery'
import { useFocusAreasStore } from '@/stores/focusAreas'
import type { Decision, DecisionCategory, DecisionOption, DecisionStatus } from '@/types'

const authStore = useAuthStore()
const decisionsStore = useDecisionsStore()
const discoveryStore = useDiscoveryStore()
const focusAreasStore = useFocusAreasStore()

const showAddDecision = ref(false)
const expandedDecisionId = ref<string | null>(null)
const showMakeDecision = ref<string | null>(null)
const selectedOptionId = ref<string | null>(null)
const decisionRationale = ref('')
const filterStatus = ref<DecisionStatus | 'all'>('all')
const filterCategory = ref<DecisionCategory | 'all'>('all')

// Evidence linking state
const linkingHypothesesForDecision = ref<string | null>(null)
const selectedHypothesisIds = ref<string[]>([])

const decisionForm = ref({
  title: '',
  context: '',
  category: 'product' as DecisionCategory,
  owner: '',
  options: [] as Omit<DecisionOption, 'id'>[],
})

const categories: { value: DecisionCategory; label: string }[] = [
  { value: 'product', label: 'Product' },
  { value: 'technical', label: 'Technical' },
  { value: 'process', label: 'Process' },
  { value: 'strategy', label: 'Strategy' },
]

const statuses: { value: DecisionStatus | 'all'; label: string }[] = [
  { value: 'all', label: 'All' },
  { value: 'proposed', label: 'Proposed' },
  { value: 'decided', label: 'Decided' },
  { value: 'revisited', label: 'Revisited' },
]

const filteredDecisions = ref<Decision[]>([])

function updateFilteredDecisions() {
  let result = [...decisionsStore.decisions]

  if (filterStatus.value !== 'all') {
    result = result.filter((d) => d.status === filterStatus.value)
  }

  if (filterCategory.value !== 'all') {
    result = result.filter((d) => d.category === filterCategory.value)
  }

  filteredDecisions.value = result
}

onMounted(() => {
  decisionsStore.subscribe()
  discoveryStore.subscribe()
  focusAreasStore.subscribe()
})

onUnmounted(() => {
  decisionsStore.unsubscribe()
  discoveryStore.unsubscribe()
  focusAreasStore.unsubscribe()
})

watch([() => decisionsStore.decisions, filterStatus, filterCategory], updateFilteredDecisions, { immediate: true })

// Get icon and color for decision type
function getDecisionIcon(decision: Decision) {
  if (decision.autoGenerated) {
    return {
      icon: 'M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z',
      bgColor: 'bg-purple-100',
      iconColor: 'text-purple-600',
    }
  }

  switch (decision.status) {
    case 'decided':
      return {
        icon: 'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z',
        bgColor: 'bg-green-100',
        iconColor: 'text-green-600',
      }
    case 'revisited':
      return {
        icon: 'M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15',
        bgColor: 'bg-amber-100',
        iconColor: 'text-amber-600',
      }
    default:
      return {
        icon: 'M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z',
        bgColor: 'bg-blue-100',
        iconColor: 'text-blue-600',
      }
  }
}

// Get category icon
function getCategoryIcon(category: DecisionCategory) {
  switch (category) {
    case 'product':
      return 'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4'
    case 'technical':
      return 'M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4'
    case 'process':
      return 'M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z'
    case 'strategy':
      return 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z'
    default:
      return 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2'
  }
}

function addOptionToForm() {
  decisionForm.value.options.push({
    title: '',
    description: '',
    pros: [],
    cons: [],
    selected: false,
  })
}

function removeOptionFromForm(index: number) {
  decisionForm.value.options.splice(index, 1)
}

function addProToOption(optionIndex: number) {
  const option = decisionForm.value.options[optionIndex]
  if (option) option.pros.push('')
}

function removeProFromOption(optionIndex: number, proIndex: number) {
  const option = decisionForm.value.options[optionIndex]
  if (option) option.pros.splice(proIndex, 1)
}

function addConToOption(optionIndex: number) {
  const option = decisionForm.value.options[optionIndex]
  if (option) option.cons.push('')
}

function removeConFromOption(optionIndex: number, conIndex: number) {
  const option = decisionForm.value.options[optionIndex]
  if (option) option.cons.splice(conIndex, 1)
}

async function handleSubmitDecision() {
  if (!decisionForm.value.title.trim()) return

  const cleanedOptions = decisionForm.value.options
    .filter((opt) => opt.title.trim())
    .map((opt) => ({
      ...opt,
      pros: opt.pros.filter((p) => p.trim()),
      cons: opt.cons.filter((c) => c.trim()),
    }))

  await decisionsStore.addDecision({
    title: decisionForm.value.title,
    context: decisionForm.value.context,
    category: decisionForm.value.category,
    owner: decisionForm.value.owner,
    options: cleanedOptions,
  })

  resetDecisionForm()
  showAddDecision.value = false
}

function resetDecisionForm() {
  decisionForm.value = {
    title: '',
    context: '',
    category: 'product',
    owner: '',
    options: [],
  }
}

function startMakeDecision(decisionId: string) {
  showMakeDecision.value = decisionId
  selectedOptionId.value = null
  decisionRationale.value = ''
}

async function handleMakeDecision(decisionId: string) {
  if (!selectedOptionId.value) return

  await decisionsStore.makeDecision(decisionId, selectedOptionId.value, decisionRationale.value)
  showMakeDecision.value = null
  selectedOptionId.value = null
  decisionRationale.value = ''
}

async function handleRevisitDecision(id: string) {
  await decisionsStore.revisitDecision(id)
}

async function handleReopenDecision(id: string) {
  await decisionsStore.reopenDecision(id)
}

async function handleDeleteDecision(id: string) {
  if (!confirm('Delete this decision and all its options?')) return
  await decisionsStore.deleteDecision(id)
}

function toggleExpand(id: string) {
  expandedDecisionId.value = expandedDecisionId.value === id ? null : id
}

function formatDate(timestamp: { toDate: () => Date } | null | undefined) {
  if (!timestamp) return ''
  const date = timestamp.toDate()
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })
}

function formatRelativeTime(timestamp: { toDate: () => Date } | null | undefined) {
  if (!timestamp) return ''
  const date = timestamp.toDate()
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffMins = Math.floor(diffMs / 60000)
  const diffHours = Math.floor(diffMs / 3600000)
  const diffDays = Math.floor(diffMs / 86400000)

  if (diffMins < 1) return 'just now'
  if (diffMins < 60) return `${diffMins}m ago`
  if (diffHours < 24) return `${diffHours}h ago`
  if (diffDays < 7) return `${diffDays}d ago`
  return formatDate(timestamp)
}

// Evidence linking functions
function startLinkingHypotheses(decisionId: string) {
  const decision = decisionsStore.decisions.find(d => d.id === decisionId)
  linkingHypothesesForDecision.value = decisionId
  selectedHypothesisIds.value = decision?.relatedHypothesisIds ? [...decision.relatedHypothesisIds] : []
}

function cancelLinkingHypotheses() {
  linkingHypothesesForDecision.value = null
  selectedHypothesisIds.value = []
}

function toggleHypothesisSelection(hypothesisId: string) {
  const idx = selectedHypothesisIds.value.indexOf(hypothesisId)
  if (idx >= 0) {
    selectedHypothesisIds.value.splice(idx, 1)
  } else {
    selectedHypothesisIds.value.push(hypothesisId)
  }
}

async function saveLinkHypotheses(decisionId: string) {
  await decisionsStore.linkHypothesesToDecision(decisionId, selectedHypothesisIds.value)
  linkingHypothesesForDecision.value = null
  selectedHypothesisIds.value = []
}

function getHypothesisBelief(id: string) {
  const hypothesis = discoveryStore.hypotheses.find(h => h.id === id)
  return hypothesis?.belief || 'Unknown hypothesis'
}

function getHypothesisStatus(id: string) {
  const hypothesis = discoveryStore.hypotheses.find(h => h.id === id)
  return hypothesis?.status || 'unknown'
}

function getFocusAreaTitle(id?: string) {
  if (!id) return null
  const fa = focusAreasStore.focusAreas.find(f => f.id === id)
  return fa?.title
}

function getStatusBadgeClass(status: string) {
  switch (status) {
    case 'active':
      return 'badge-blue'
    case 'validated':
      return 'badge-green'
    case 'invalidated':
      return 'badge-red'
    case 'parked':
      return 'badge-gray'
    default:
      return 'badge-gray'
  }
}

function getSelectedOption(decision: Decision) {
  return decision.options.find(o => o.selected)
}

// Simple markdown parser for bold, italic, and line breaks
function parseMarkdown(text: string): string {
  if (!text) return ''
  return text
    // Bold: **text** or __text__
    .replace(/\*\*(.+?)\*\*/g, '<strong class="font-semibold text-gray-900">$1</strong>')
    .replace(/__(.+?)__/g, '<strong class="font-semibold text-gray-900">$1</strong>')
    // Italic: *text* or _text_
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/_(.+?)_/g, '<em>$1</em>')
    // Horizontal rule: ---
    .replace(/^---$/gm, '<hr class="my-3 border-gray-200">')
    // Line breaks
    .replace(/\n/g, '<br>')
}

// Get plain text preview (strip markdown)
function getPlainTextPreview(text: string, maxLength: number = 150): string {
  if (!text) return ''
  const plain = text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/__(.+?)__/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/_(.+?)_/g, '$1')
    .replace(/^---$/gm, '')
    .replace(/\n+/g, ' ')
    .trim()
  return plain.length > maxLength ? plain.substring(0, maxLength) + '...' : plain
}

// Stats
const stats = computed(() => ({
  proposed: decisionsStore.proposedDecisions.length,
  decided: decisionsStore.decidedDecisions.length,
  revisited: decisionsStore.revisitedDecisions.length,
  total: decisionsStore.decisions.length,
}))
</script>

<template>
  <div class="space-y-6">
    <!-- Header with stats -->
    <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
      <div>
        <p class="text-sm text-gray-500">Record consequential choices with context, options, and rationale.</p>
      </div>

      <!-- Quick stats -->
      <div class="flex items-center gap-4">
        <div class="flex items-center gap-6 text-sm">
          <div class="flex items-center gap-2">
            <span class="w-2 h-2 rounded-full bg-blue-500"></span>
            <span class="text-gray-600">{{ stats.proposed }} proposed</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="w-2 h-2 rounded-full bg-green-500"></span>
            <span class="text-gray-600">{{ stats.decided }} decided</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="w-2 h-2 rounded-full bg-amber-500"></span>
            <span class="text-gray-600">{{ stats.revisited }} revisited</span>
          </div>
        </div>

        <button
          v-if="authStore.canEdit && !showAddDecision"
          class="btn-primary text-sm"
          @click="showAddDecision = true"
        >
          Add Decision
        </button>
      </div>
    </div>

    <!-- Filters -->
    <div class="flex flex-wrap gap-3">
      <div>
        <label class="text-xs text-gray-500 block mb-1">Status</label>
        <select v-model="filterStatus" class="input text-sm py-1.5">
          <option v-for="s in statuses" :key="s.value" :value="s.value">
            {{ s.label }}
          </option>
        </select>
      </div>
      <div>
        <label class="text-xs text-gray-500 block mb-1">Category</label>
        <select v-model="filterCategory" class="input text-sm py-1.5">
          <option value="all">All</option>
          <option v-for="c in categories" :key="c.value" :value="c.value">
            {{ c.label }}
          </option>
        </select>
      </div>
    </div>

    <!-- Add Decision Form -->
    <div v-if="showAddDecision" class="card p-6 space-y-4">
      <h3 class="font-medium text-gray-900">New Decision</h3>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="md:col-span-2">
          <label class="label">Decision Title</label>
          <input
            v-model="decisionForm.title"
            class="input"
            placeholder="What decision needs to be made?"
          />
        </div>

        <div class="md:col-span-2">
          <label class="label">Context</label>
          <textarea
            v-model="decisionForm.context"
            class="input min-h-[80px]"
            placeholder="What's the background? Why is this decision needed now?"
          />
        </div>

        <div>
          <label class="label">Category</label>
          <select v-model="decisionForm.category" class="input">
            <option v-for="c in categories" :key="c.value" :value="c.value">
              {{ c.label }}
            </option>
          </select>
        </div>

        <div>
          <label class="label">Owner</label>
          <input
            v-model="decisionForm.owner"
            class="input"
            placeholder="Who's responsible for this decision?"
          />
        </div>
      </div>

      <!-- Options -->
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <label class="label mb-0">Options Considered</label>
          <button
            type="button"
            class="btn-ghost text-sm"
            @click="addOptionToForm"
          >
            + Add Option
          </button>
        </div>

        <div
          v-for="(option, optIndex) in decisionForm.options"
          :key="optIndex"
          class="p-4 bg-gray-50 rounded-lg space-y-3"
        >
          <div class="flex items-center justify-between">
            <span class="text-xs font-medium text-gray-500">Option {{ optIndex + 1 }}</span>
            <button
              type="button"
              class="text-gray-400 hover:text-red-600"
              @click="removeOptionFromForm(optIndex)"
            >
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          <input
            v-model="option.title"
            class="input"
            placeholder="Option name"
          />

          <textarea
            v-model="option.description"
            class="input min-h-[60px]"
            placeholder="Describe this option..."
          />

          <div class="grid grid-cols-2 gap-4">
            <!-- Pros -->
            <div>
              <div class="flex items-center justify-between mb-2">
                <span class="text-xs font-medium text-green-600">Pros</span>
                <button
                  type="button"
                  class="text-xs text-green-600 hover:text-green-700"
                  @click="addProToOption(optIndex)"
                >
                  + Add
                </button>
              </div>
              <div class="space-y-2">
                <div
                  v-for="(_, proIndex) in option.pros"
                  :key="proIndex"
                  class="flex gap-2"
                >
                  <input
                    v-model="option.pros[proIndex]"
                    class="input flex-1"
                    placeholder="Pro..."
                  />
                  <button
                    type="button"
                    class="text-gray-400 hover:text-red-600"
                    @click="removeProFromOption(optIndex, proIndex)"
                  >
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>

            <!-- Cons -->
            <div>
              <div class="flex items-center justify-between mb-2">
                <span class="text-xs font-medium text-red-600">Cons</span>
                <button
                  type="button"
                  class="text-xs text-red-600 hover:text-red-700"
                  @click="addConToOption(optIndex)"
                >
                  + Add
                </button>
              </div>
              <div class="space-y-2">
                <div
                  v-for="(_, conIndex) in option.cons"
                  :key="conIndex"
                  class="flex gap-2"
                >
                  <input
                    v-model="option.cons[conIndex]"
                    class="input flex-1"
                    placeholder="Con..."
                  />
                  <button
                    type="button"
                    class="text-gray-400 hover:text-red-600"
                    @click="removeConFromOption(optIndex, conIndex)"
                  >
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <p v-if="decisionForm.options.length === 0" class="text-sm text-gray-400 italic">
          No options added yet. Click "Add Option" to document the alternatives being considered.
        </p>
      </div>

      <div class="flex gap-2 justify-end pt-2">
        <button class="btn-ghost" @click="showAddDecision = false; resetDecisionForm()">
          Cancel
        </button>
        <button
          class="btn-primary"
          :disabled="decisionsStore.saving || !decisionForm.title.trim()"
          @click="handleSubmitDecision"
        >
          {{ decisionsStore.saving ? 'Saving...' : 'Create Decision' }}
        </button>
      </div>
    </div>

    <!-- Loading state -->
    <div v-if="decisionsStore.loading" class="text-sm text-gray-500">Loading...</div>

    <template v-else>
      <!-- No decisions -->
      <div v-if="filteredDecisions.length === 0" class="card p-8 text-center">
        <div class="w-12 h-12 rounded-full bg-gray-100 flex items-center justify-center mx-auto mb-4">
          <svg class="w-6 h-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
          </svg>
        </div>
        <p class="text-sm text-gray-500">No decisions found.</p>
        <p class="text-xs text-gray-400 mt-1">Add a decision to start documenting choices.</p>
      </div>

      <!-- Timeline Feed -->
      <div v-else class="flow-root">
        <ul role="list" class="-mb-8">
          <li v-for="(decision, index) in filteredDecisions" :key="decision.id">
            <div class="relative pb-8">
              <!-- Timeline connector -->
              <span
                v-if="index !== filteredDecisions.length - 1"
                class="absolute left-5 top-5 -ml-px h-full w-0.5 bg-gray-200"
                aria-hidden="true"
              />

              <div class="relative flex items-start space-x-3">
                <!-- Icon -->
                <div class="relative">
                  <div
                    :class="[
                      'flex size-10 items-center justify-center rounded-full ring-8 ring-white',
                      getDecisionIcon(decision).bgColor
                    ]"
                  >
                    <svg
                      :class="['size-5', getDecisionIcon(decision).iconColor]"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="getDecisionIcon(decision).icon" />
                    </svg>
                  </div>
                  <!-- Category badge on icon -->
                  <span class="absolute -bottom-0.5 -right-1 rounded-tl bg-white px-0.5 py-px">
                    <svg class="size-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="getCategoryIcon(decision.category)" />
                    </svg>
                  </span>
                </div>

                <!-- Content -->
                <div class="min-w-0 flex-1">
                  <!-- Header -->
                  <div>
                    <div class="flex items-center gap-2 flex-wrap">
                      <button
                        class="text-sm font-medium text-gray-900 hover:text-accent-600 text-left"
                        @click="toggleExpand(decision.id)"
                      >
                        {{ decision.title.replace('[Auto] ', '') }}
                      </button>
                      <span v-if="decision.autoGenerated" class="feed-badge feed-badge-purple">
                        <svg viewBox="0 0 6 6" aria-hidden="true" class="size-1.5 fill-purple-500">
                          <circle r="3" cx="3" cy="3" />
                        </svg>
                        Auto
                      </span>
                      <span :class="['feed-badge', `feed-badge-${decision.status}`]">
                        <svg viewBox="0 0 6 6" aria-hidden="true" :class="['size-1.5', `fill-${decision.status}`]">
                          <circle r="3" cx="3" cy="3" />
                        </svg>
                        {{ decision.status }}
                      </span>
                      <span class="feed-badge feed-badge-category">
                        {{ decision.category }}
                      </span>
                    </div>
                    <p class="mt-0.5 text-sm text-gray-500">
                      <span v-if="decision.owner">{{ decision.owner }} · </span>
                      <span>{{ formatRelativeTime(decision.createdAt) }}</span>
                      <span v-if="decision.decidedAt"> · Decided {{ formatRelativeTime(decision.decidedAt) }}</span>
                    </p>
                  </div>

                  <!-- Summary content -->
                  <div class="mt-2 text-sm text-gray-700">
                    <p v-if="decision.context" class="line-clamp-2">{{ getPlainTextPreview(decision.context) }}</p>

                    <!-- Selected option preview for decided -->
                    <div v-if="decision.status === 'decided' && getSelectedOption(decision)" class="mt-2 flex items-center gap-2">
                      <svg class="w-4 h-4 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                      </svg>
                      <span class="text-green-700 font-medium">{{ getSelectedOption(decision)?.title }}</span>
                    </div>

                    <!-- Quick links -->
                    <div class="mt-2 flex items-center gap-3 text-xs">
                      <span v-if="decision.options.length > 0" class="text-gray-500">
                        {{ decision.options.length }} option{{ decision.options.length !== 1 ? 's' : '' }}
                      </span>
                      <span v-if="decision.relatedHypothesisIds && decision.relatedHypothesisIds.length > 0" class="text-indigo-600">
                        {{ decision.relatedHypothesisIds.length }} hypothesis{{ decision.relatedHypothesisIds.length !== 1 ? 'es' : '' }} linked
                      </span>
                      <span v-if="decision.focusAreaId" class="text-blue-600">
                        Focus area linked
                      </span>
                    </div>
                  </div>

                  <!-- Quick Actions -->
                  <div v-if="authStore.canEdit" class="mt-3 flex items-center gap-2">
                    <button
                      class="text-xs text-gray-500 hover:text-gray-700"
                      @click="toggleExpand(decision.id)"
                    >
                      {{ expandedDecisionId === decision.id ? 'Collapse' : 'Expand' }}
                    </button>
                    <span class="text-gray-300">·</span>
                    <button
                      v-if="decision.status === 'proposed'"
                      class="text-xs text-accent-600 hover:text-accent-700 font-medium"
                      @click="startMakeDecision(decision.id)"
                    >
                      Make Decision
                    </button>
                    <button
                      v-if="decision.status === 'decided'"
                      class="text-xs text-amber-600 hover:text-amber-700"
                      @click="handleRevisitDecision(decision.id)"
                    >
                      Revisit
                    </button>
                    <button
                      v-if="decision.status === 'revisited'"
                      class="text-xs text-blue-600 hover:text-blue-700"
                      @click="handleReopenDecision(decision.id)"
                    >
                      Reopen
                    </button>
                    <span class="text-gray-300">·</span>
                    <button
                      class="text-xs text-red-500 hover:text-red-700"
                      @click="handleDeleteDecision(decision.id)"
                    >
                      Delete
                    </button>
                  </div>

                  <!-- Expanded Content -->
                  <Transition name="slide-down">
                    <div v-if="expandedDecisionId === decision.id" class="mt-4 space-y-4 border-t pt-4">
                      <!-- Make Decision UI -->
                      <div v-if="showMakeDecision === decision.id && decision.status === 'proposed'" class="p-4 bg-accent-50 border border-accent-200 rounded-lg space-y-4">
                        <h4 class="font-medium text-gray-900">Make Decision</h4>
                        <p class="text-sm text-gray-600">Select the chosen option and provide rationale.</p>

                        <div class="space-y-2">
                          <div
                            v-for="option in decision.options"
                            :key="option.id"
                            :class="[
                              'p-3 rounded-lg border-2 cursor-pointer transition-colors',
                              selectedOptionId === option.id
                                ? 'border-accent-500 bg-accent-50'
                                : 'border-gray-200 hover:border-gray-300'
                            ]"
                            @click="selectedOptionId = option.id"
                          >
                            <div class="flex items-center gap-2">
                              <div
                                :class="[
                                  'w-4 h-4 rounded-full border-2 flex items-center justify-center',
                                  selectedOptionId === option.id ? 'border-accent-500' : 'border-gray-300'
                                ]"
                              >
                                <div
                                  v-if="selectedOptionId === option.id"
                                  class="w-2 h-2 rounded-full bg-accent-500"
                                />
                              </div>
                              <span class="font-medium text-gray-900">{{ option.title }}</span>
                            </div>
                          </div>
                        </div>

                        <div>
                          <label class="label">Rationale</label>
                          <textarea
                            v-model="decisionRationale"
                            class="input min-h-[80px]"
                            placeholder="Why was this option chosen?"
                          />
                        </div>

                        <div class="flex gap-2 justify-end">
                          <button class="btn-ghost" @click="showMakeDecision = null">Cancel</button>
                          <button
                            class="btn-primary"
                            :disabled="!selectedOptionId"
                            @click="handleMakeDecision(decision.id)"
                          >
                            Confirm Decision
                          </button>
                        </div>
                      </div>

                      <!-- Context -->
                      <div v-if="decision.context">
                        <h4 class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Context</h4>
                        <div class="text-sm text-gray-700 prose prose-sm max-w-none" v-html="parseMarkdown(decision.context)"></div>
                      </div>

                      <!-- Options -->
                      <div>
                        <h4 class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-3">
                          Options Considered
                        </h4>

                        <div v-if="decision.options.length === 0" class="text-sm text-gray-400 italic">
                          No options documented.
                        </div>

                        <div v-else class="space-y-3">
                          <div
                            v-for="option in decision.options"
                            :key="option.id"
                            :class="[
                              'p-4 rounded-lg border',
                              option.selected ? 'border-green-300 bg-green-50' : 'border-gray-200'
                            ]"
                          >
                            <div class="flex items-center gap-2 mb-2">
                              <span class="font-medium text-gray-900">{{ option.title }}</span>
                              <span v-if="option.selected" class="feed-badge feed-badge-decided">
                                <svg viewBox="0 0 6 6" aria-hidden="true" class="size-1.5 fill-green-500">
                                  <circle r="3" cx="3" cy="3" />
                                </svg>
                                Selected
                              </span>
                            </div>

                            <p v-if="option.description" class="text-sm text-gray-600 mb-3">
                              {{ option.description }}
                            </p>

                            <div class="grid grid-cols-2 gap-4 text-sm">
                              <div v-if="option.pros.length > 0">
                                <span class="text-xs font-medium text-green-600">Pros</span>
                                <ul class="mt-1 space-y-1">
                                  <li v-for="(pro, i) in option.pros" :key="i" class="flex items-start gap-1">
                                    <svg class="w-4 h-4 text-green-500 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                                    </svg>
                                    <span class="text-gray-600">{{ pro }}</span>
                                  </li>
                                </ul>
                              </div>

                              <div v-if="option.cons.length > 0">
                                <span class="text-xs font-medium text-red-600">Cons</span>
                                <ul class="mt-1 space-y-1">
                                  <li v-for="(con, i) in option.cons" :key="i" class="flex items-start gap-1">
                                    <svg class="w-4 h-4 text-red-500 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                    </svg>
                                    <span class="text-gray-600">{{ con }}</span>
                                  </li>
                                </ul>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <!-- Rationale -->
                      <div v-if="decision.status === 'decided' && decision.rationale">
                        <h4 class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Rationale</h4>
                        <div class="text-sm text-gray-700 prose prose-sm max-w-none" v-html="parseMarkdown(decision.rationale)"></div>
                      </div>

                      <!-- Outcome -->
                      <div v-if="decision.outcome">
                        <h4 class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Outcome</h4>
                        <div class="text-sm text-gray-700 prose prose-sm max-w-none" v-html="parseMarkdown(decision.outcome)"></div>
                      </div>

                      <!-- Related Focus Area -->
                      <div v-if="decision.focusAreaId">
                        <h4 class="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Related Focus Area</h4>
                        <RouterLink
                          to="/focus-areas"
                          class="inline-flex items-center gap-2 px-3 py-1.5 bg-indigo-50 text-indigo-700 rounded-md text-sm hover:bg-indigo-100 transition-colors"
                        >
                          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                          </svg>
                          {{ getFocusAreaTitle(decision.focusAreaId) || 'View Focus Area' }}
                        </RouterLink>
                      </div>

                      <!-- Linked Hypotheses -->
                      <div>
                        <div class="flex items-center justify-between mb-2">
                          <h4 class="text-xs font-medium text-gray-500 uppercase tracking-wide">
                            Supporting Evidence
                          </h4>
                          <button
                            v-if="authStore.canEdit && linkingHypothesesForDecision !== decision.id"
                            class="text-xs text-indigo-600 hover:text-indigo-700"
                            @click.stop="startLinkingHypotheses(decision.id)"
                          >
                            + Link Hypotheses
                          </button>
                        </div>

                        <!-- Linking UI -->
                        <div v-if="linkingHypothesesForDecision === decision.id" class="p-4 bg-indigo-50 border border-indigo-200 rounded-lg space-y-3">
                          <p class="text-sm text-gray-600">Select hypotheses that informed this decision:</p>

                          <div class="max-h-64 overflow-y-auto space-y-2">
                            <div
                              v-for="hypothesis in discoveryStore.hypotheses"
                              :key="hypothesis.id"
                              :class="[
                                'p-3 rounded-lg border-2 cursor-pointer transition-colors',
                                selectedHypothesisIds.includes(hypothesis.id)
                                  ? 'border-indigo-500 bg-white'
                                  : 'border-gray-200 bg-white hover:border-gray-300'
                              ]"
                              @click="toggleHypothesisSelection(hypothesis.id)"
                            >
                              <div class="flex items-start gap-2">
                                <div
                                  :class="[
                                    'w-4 h-4 rounded border-2 flex-shrink-0 mt-0.5 flex items-center justify-center',
                                    selectedHypothesisIds.includes(hypothesis.id) ? 'border-indigo-500 bg-indigo-500' : 'border-gray-300'
                                  ]"
                                >
                                  <svg
                                    v-if="selectedHypothesisIds.includes(hypothesis.id)"
                                    class="w-3 h-3 text-white"
                                    fill="none"
                                    stroke="currentColor"
                                    viewBox="0 0 24 24"
                                  >
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                                  </svg>
                                </div>
                                <div class="flex-1 min-w-0">
                                  <div class="flex items-center gap-2 mb-1">
                                    <span :class="getStatusBadgeClass(hypothesis.status)">{{ hypothesis.status }}</span>
                                  </div>
                                  <p class="text-sm text-gray-900">{{ hypothesis.belief }}</p>
                                </div>
                              </div>
                            </div>
                          </div>

                          <div v-if="discoveryStore.hypotheses.length === 0" class="text-sm text-gray-500 text-center py-4">
                            No hypotheses available.
                          </div>

                          <div class="flex gap-2 justify-end pt-2">
                            <button class="btn-ghost text-sm" @click.stop="cancelLinkingHypotheses">Cancel</button>
                            <button
                              class="btn-primary text-sm"
                              @click.stop="saveLinkHypotheses(decision.id)"
                            >
                              Save ({{ selectedHypothesisIds.length }})
                            </button>
                          </div>
                        </div>

                        <!-- Display linked hypotheses -->
                        <div v-else-if="decision.relatedHypothesisIds && decision.relatedHypothesisIds.length > 0" class="space-y-2">
                          <RouterLink
                            v-for="hypId in decision.relatedHypothesisIds"
                            :key="hypId"
                            to="/discovery"
                            class="block p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                          >
                            <div class="flex items-center gap-2 mb-1">
                              <span :class="getStatusBadgeClass(getHypothesisStatus(hypId))">{{ getHypothesisStatus(hypId) }}</span>
                              <span v-if="decision.sourceHypothesisId === hypId" class="text-xs text-purple-600">(source)</span>
                            </div>
                            <p class="text-sm text-gray-700">{{ getHypothesisBelief(hypId) }}</p>
                          </RouterLink>
                        </div>

                        <p v-else class="text-sm text-gray-400 italic">
                          No evidence linked yet.
                        </p>
                      </div>
                    </div>
                  </Transition>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </template>

    <!-- Error display -->
    <div v-if="decisionsStore.error" class="p-3 bg-red-50 border border-red-200 rounded-md text-sm text-red-600">
      {{ decisionsStore.error }}
    </div>
  </div>
</template>

<style scoped>
/* Feed badges */
.feed-badge {
  @apply inline-flex items-center gap-x-1.5 rounded-full px-2 py-0.5 text-xs font-medium ring-1 ring-inset;
}

.feed-badge-purple {
  @apply text-purple-700 ring-purple-200 bg-purple-50;
}

.feed-badge-proposed {
  @apply text-blue-700 ring-blue-200 bg-blue-50;
}

.feed-badge-decided {
  @apply text-green-700 ring-green-200 bg-green-50;
}

.feed-badge-revisited {
  @apply text-amber-700 ring-amber-200 bg-amber-50;
}

.feed-badge-category {
  @apply text-gray-600 ring-gray-200 bg-gray-50;
}

.fill-proposed {
  @apply fill-blue-500;
}

.fill-decided {
  @apply fill-green-500;
}

.fill-revisited {
  @apply fill-amber-500;
}

/* Status badges */
.badge-blue {
  @apply px-2 py-0.5 text-xs font-medium rounded-full bg-blue-100 text-blue-700;
}
.badge-green {
  @apply px-2 py-0.5 text-xs font-medium rounded-full bg-green-100 text-green-700;
}
.badge-red {
  @apply px-2 py-0.5 text-xs font-medium rounded-full bg-red-100 text-red-700;
}
.badge-gray {
  @apply px-2 py-0.5 text-xs font-medium rounded-full bg-gray-100 text-gray-700;
}

/* Slide down transition */
.slide-down-enter-active,
.slide-down-leave-active {
  transition: all 0.2s ease-out;
}

.slide-down-enter-from,
.slide-down-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>
