<script setup lang="ts">
import { computed, onMounted, onUnmounted } from 'vue'
import { RouterLink } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { useFocusAreasStore } from '@/stores/focusAreas'
import { useDiscoveryStore } from '@/stores/discovery'
import { useDeliveryStore } from '@/stores/delivery'
import { useVisionStore } from '@/stores/vision'
import { useCustomerArchetypesStore } from '@/stores/customerArchetypes'
import { useObjectivesStore } from '@/stores/objectives'
import { useDecisionsStore } from '@/stores/decisions'
import { useDesignPartnersStore } from '@/stores/designPartners'

useAuthStore() // Check auth status
const focusAreasStore = useFocusAreasStore()
const discoveryStore = useDiscoveryStore()
const deliveryStore = useDeliveryStore()
const visionStore = useVisionStore()
const archetypesStore = useCustomerArchetypesStore()
const objectivesStore = useObjectivesStore()
const decisionsStore = useDecisionsStore()
const designPartnersStore = useDesignPartnersStore()

const loading = computed(() =>
  focusAreasStore.loading || discoveryStore.loading || deliveryStore.loading ||
  archetypesStore.loading || objectivesStore.loading || decisionsStore.loading ||
  designPartnersStore.loading
)

// Calculate metrics for the last 30 days
const thirtyDaysAgo = new Date()
thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30)

// Strategic Focus Metrics
const focusAreaMetrics = computed(() => {
  const areas = focusAreasStore.activeFocusAreas
  return {
    total: areas.length,
    highConfidence: areas.filter(fa => fa.confidenceLevel === 'high').length,
    mediumConfidence: areas.filter(fa => fa.confidenceLevel === 'medium').length,
    lowConfidence: areas.filter(fa => fa.confidenceLevel === 'low').length,
    improving: areas.filter(fa => fa.confidenceTrend === 'improving').length,
    declining: areas.filter(fa => fa.confidenceTrend === 'declining').length,
    avgProgress: areas.length > 0
      ? Math.round(areas.reduce((sum, fa) => sum + (fa.progressPercentage || 0), 0) / areas.length)
      : 0,
  }
})

// Discovery Velocity Metrics
const discoveryMetrics = computed(() => {
  const oneWeekAgo = new Date()
  oneWeekAgo.setDate(oneWeekAgo.getDate() - 7)
  const twoWeeksAgo = new Date()
  twoWeeksAgo.setDate(twoWeeksAgo.getDate() - 14)

  const resolvedThisWeek = discoveryStore.hypotheses.filter(h => {
    if (h.status !== 'validated' && h.status !== 'invalidated') return false
    if (!h.updatedAt) return false
    return h.updatedAt.toDate() >= oneWeekAgo
  }).length

  const resolvedLastWeek = discoveryStore.hypotheses.filter(h => {
    if (h.status !== 'validated' && h.status !== 'invalidated') return false
    if (!h.updatedAt) return false
    const date = h.updatedAt.toDate()
    return date >= twoWeeksAgo && date < oneWeekAgo
  }).length

  const validatedAll = discoveryStore.validatedHypotheses.length
  const invalidatedAll = discoveryStore.invalidatedHypotheses.length
  const resolvedAll = validatedAll + invalidatedAll

  return {
    active: discoveryStore.activeHypotheses.length,
    validated: validatedAll,
    invalidated: invalidatedAll,
    validationRate: resolvedAll > 0 ? Math.round((validatedAll / resolvedAll) * 100) : 0,
    resolvedThisWeek,
    velocityChange: resolvedLastWeek > 0
      ? Math.round(((resolvedThisWeek - resolvedLastWeek) / resolvedLastWeek) * 100)
      : resolvedThisWeek > 0 ? 100 : 0,
    withStrongEvidence: discoveryStore.hypothesesWithStrongEvidence.length,
    highPriority: discoveryStore.highPriorityHypotheses.length,
  }
})

// Customer Discovery Health
const customerMetrics = computed(() => {
  const archetypes = archetypesStore.activeArchetypes
  const totalInterviews = archetypes.reduce((sum, a) => sum + a.interviewNotes.length, 0)
  const avgInterviews = archetypes.length > 0 ? Math.round(totalInterviews / archetypes.length) : 0
  const withSufficientInterviews = archetypes.filter(a =>
    a.interviewNotes.length >= a.interviewTarget
  ).length
  const avgConfidence = archetypes.length > 0
    ? Math.round(archetypes.reduce((sum, a) => sum + a.confidenceScore, 0) / archetypes.length)
    : 0

  return {
    totalArchetypes: archetypes.length,
    totalInterviews,
    avgInterviews,
    withSufficientInterviews,
    avgConfidence,
    activePartners: designPartnersStore.activePartners.length,
  }
})

// Decision Effectiveness
const decisionMetrics = computed(() => {
  const decided = decisionsStore.decidedDecisions
  const withEvidence = decided.filter(d =>
    d.relatedHypothesisIds && d.relatedHypothesisIds.length > 0
  ).length

  return {
    proposed: decisionsStore.proposedDecisions.length,
    decided: decided.length,
    withEvidence,
    evidenceRate: decided.length > 0 ? Math.round((withEvidence / decided.length) * 100) : 0,
    autoGenerated: decisionsStore.autoGeneratedDecisions.length,
    needingRetrospective: decisionsStore.decisionsNeedingRetrospective.length,
    inProgress: decisionsStore.decisionsInProgress.length,
    completed: decisionsStore.decisionsCompleted.length,
  }
})

// Strategic Alignment Score
const alignmentScore = computed(() => {
  // OKRs linked to Focus Areas
  const objectivesWithFocus = objectivesStore.activeObjectives.filter(o =>
    o.focusAreaIds && o.focusAreaIds.length > 0
  ).length
  const objectivesTotal = objectivesStore.activeObjectives.length
  const objectivesAlignment = objectivesTotal > 0
    ? Math.round((objectivesWithFocus / objectivesTotal) * 100) : 0

  // Decisions with evidence
  const decisionsWithEvidence = decisionsStore.decidedDecisions.filter(d =>
    d.relatedHypothesisIds && d.relatedHypothesisIds.length > 0
  ).length
  const decisionsTotal = decisionsStore.decidedDecisions.length
  const decisionsAlignment = decisionsTotal > 0
    ? Math.round((decisionsWithEvidence / decisionsTotal) * 100) : 0

  // Focus areas with target archetypes
  const focusWithArchetypes = focusAreasStore.activeFocusAreas.filter(fa =>
    fa.targetArchetypeIds && fa.targetArchetypeIds.length > 0
  ).length
  const focusTotal = focusAreasStore.activeFocusAreas.length
  const focusAlignment = focusTotal > 0
    ? Math.round((focusWithArchetypes / focusTotal) * 100) : 0

  // Calculate overall score (weighted average)
  const overallScore = Math.round(
    (objectivesAlignment * 0.4 + decisionsAlignment * 0.35 + focusAlignment * 0.25)
  )

  return {
    objectivesAlignment,
    decisionsAlignment,
    focusAlignment,
    overallScore,
  }
})

// Risk Indicators
const riskIndicators = computed(() => {
  const risks: Array<{
    type: string
    message: string
    severity: 'high' | 'medium' | 'low'
    path: string
  }> = []

  // Open blockers
  if (deliveryStore.openBlockers.length > 0) {
    risks.push({
      type: 'blocker',
      message: `${deliveryStore.openBlockers.length} open blocker${deliveryStore.openBlockers.length > 1 ? 's' : ''} requiring attention`,
      severity: 'high',
      path: '/delivery',
    })
  }

  // Low confidence focus areas
  const lowConfidenceAreas = focusAreasStore.activeFocusAreas.filter(
    fa => fa.confidenceLevel === 'low'
  )
  if (lowConfidenceAreas.length > 0) {
    risks.push({
      type: 'low-confidence',
      message: `${lowConfidenceAreas.length} focus area${lowConfidenceAreas.length > 1 ? 's' : ''} with low confidence`,
      severity: 'medium',
      path: '/focus-areas',
    })
  }

  // Declining confidence trends
  const decliningAreas = focusAreasStore.activeFocusAreas.filter(
    fa => fa.confidenceTrend === 'declining'
  )
  if (decliningAreas.length > 0) {
    risks.push({
      type: 'declining-trend',
      message: `${decliningAreas.length} focus area${decliningAreas.length > 1 ? 's' : ''} with declining confidence`,
      severity: 'medium',
      path: '/focus-areas',
    })
  }

  // Unvalidated hypotheses (active > 30 days)
  const staleHypotheses = discoveryStore.activeHypotheses.filter(h => {
    if (!h.createdAt) return false
    const createdDate = h.createdAt.toDate()
    return createdDate < thirtyDaysAgo
  })
  if (staleHypotheses.length > 0) {
    risks.push({
      type: 'stale-hypotheses',
      message: `${staleHypotheses.length} hypothesis${staleHypotheses.length > 1 ? 'es' : ''} active for 30+ days`,
      severity: 'low',
      path: '/discovery',
    })
  }

  // OKRs without focus area linkage
  const orphanedOkrs = objectivesStore.activeObjectives.filter(o =>
    !o.focusAreaIds || o.focusAreaIds.length === 0
  )
  if (orphanedOkrs.length > 0) {
    risks.push({
      type: 'orphaned-okr',
      message: `${orphanedOkrs.length} OKR${orphanedOkrs.length > 1 ? 's' : ''} not linked to focus areas`,
      severity: 'low',
      path: '/objectives',
    })
  }

  return risks.sort((a, b) => {
    const severityOrder = { high: 0, medium: 1, low: 2 }
    return severityOrder[a.severity] - severityOrder[b.severity]
  })
})

// Recent Key Activities
const recentActivities = computed(() => {
  const activities: Array<{
    type: string
    title: string
    date: Date
    path: string
    icon: string
  }> = []

  // Recent validated hypotheses
  discoveryStore.validatedHypotheses.slice(0, 3).forEach(h => {
    if (h.updatedAt) {
      activities.push({
        type: 'validated',
        title: h.belief.substring(0, 60) + (h.belief.length > 60 ? '...' : ''),
        date: h.updatedAt.toDate(),
        path: '/discovery',
        icon: 'check-circle',
      })
    }
  })

  // Recent decisions made
  decisionsStore.decidedDecisions.slice(0, 3).forEach(d => {
    if (d.decidedAt) {
      activities.push({
        type: 'decided',
        title: d.title.substring(0, 60) + (d.title.length > 60 ? '...' : ''),
        date: d.decidedAt.toDate(),
        path: '/decisions',
        icon: 'scale',
      })
    }
  })

  // Recent changelog entries
  deliveryStore.changelog.slice(0, 3).forEach(c => {
    if (c.shippedAt) {
      activities.push({
        type: 'shipped',
        title: c.title,
        date: c.shippedAt.toDate(),
        path: '/delivery',
        icon: 'rocket',
      })
    }
  })

  return activities.sort((a, b) => b.date.getTime() - a.date.getTime()).slice(0, 8)
})

onMounted(() => {
  focusAreasStore.subscribe()
  discoveryStore.subscribe()
  deliveryStore.subscribe()
  visionStore.subscribe()
  archetypesStore.subscribe()
  objectivesStore.subscribe()
  decisionsStore.subscribe()
  designPartnersStore.subscribe()
})

onUnmounted(() => {
  focusAreasStore.unsubscribe()
  discoveryStore.unsubscribe()
  deliveryStore.unsubscribe()
  visionStore.unsubscribe()
  archetypesStore.unsubscribe()
  objectivesStore.unsubscribe()
  decisionsStore.unsubscribe()
  designPartnersStore.unsubscribe()
})

function formatDate(date: Date) {
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  })
}

function getScoreColor(score: number) {
  if (score >= 70) return 'text-green-600'
  if (score >= 40) return 'text-yellow-600'
  return 'text-red-600'
}

function getSeverityClass(severity: 'high' | 'medium' | 'low') {
  switch (severity) {
    case 'high':
      return 'bg-red-100 text-red-800 border-red-200'
    case 'medium':
      return 'bg-amber-100 text-amber-800 border-amber-200'
    case 'low':
      return 'bg-blue-100 text-blue-800 border-blue-200'
  }
}
</script>

<template>
  <div class="space-y-6">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Executive Dashboard</h1>
        <p class="text-sm text-gray-500 mt-1">Strategic overview and key metrics for leadership</p>
      </div>
      <RouterLink to="/" class="text-sm text-accent-600 hover:text-accent-700">
        &larr; Back to Dashboard
      </RouterLink>
    </div>

    <!-- Loading state -->
    <div v-if="loading" class="text-sm text-gray-500">Loading metrics...</div>

    <template v-else>
      <!-- Strategic Alignment Score Card -->
      <div class="bg-gradient-to-br from-indigo-600 via-purple-600 to-indigo-700 rounded-xl shadow-lg p-6 text-white">
        <div class="flex items-center justify-between">
          <div>
            <h2 class="text-lg font-medium text-white/80">Strategic Alignment Score</h2>
            <div class="flex items-baseline gap-2 mt-2">
              <span class="text-5xl font-bold">{{ alignmentScore.overallScore }}</span>
              <span class="text-xl text-white/70">/100</span>
            </div>
            <p class="text-sm text-white/60 mt-2">
              Based on OKR-focus linkage, evidence-based decisions, and customer grounding
            </p>
          </div>
          <div class="text-right space-y-2">
            <div>
              <div class="text-xs text-white/60">OKR Alignment</div>
              <div class="text-lg font-semibold">{{ alignmentScore.objectivesAlignment }}%</div>
            </div>
            <div>
              <div class="text-xs text-white/60">Evidence-Based Decisions</div>
              <div class="text-lg font-semibold">{{ alignmentScore.decisionsAlignment }}%</div>
            </div>
            <div>
              <div class="text-xs text-white/60">Customer Grounding</div>
              <div class="text-lg font-semibold">{{ alignmentScore.focusAlignment }}%</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Key Metrics Grid -->
      <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <!-- Focus Areas -->
        <div class="card p-4">
          <div class="flex items-center gap-2 mb-2">
            <svg class="w-5 h-5 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <h3 class="text-sm font-medium text-gray-500">Strategic Focus</h3>
          </div>
          <div class="text-3xl font-bold text-gray-900">{{ focusAreaMetrics.total }}</div>
          <div class="mt-2 text-xs space-y-1">
            <div class="flex justify-between">
              <span class="text-green-600">{{ focusAreaMetrics.highConfidence }} high</span>
              <span class="text-yellow-600">{{ focusAreaMetrics.mediumConfidence }} med</span>
              <span class="text-red-600">{{ focusAreaMetrics.lowConfidence }} low</span>
            </div>
            <div class="text-gray-500">
              Avg progress: {{ focusAreaMetrics.avgProgress }}%
            </div>
          </div>
        </div>

        <!-- Discovery Velocity -->
        <div class="card p-4">
          <div class="flex items-center gap-2 mb-2">
            <svg class="w-5 h-5 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
            </svg>
            <h3 class="text-sm font-medium text-gray-500">Discovery</h3>
          </div>
          <div class="text-3xl font-bold text-gray-900">{{ discoveryMetrics.active }}</div>
          <div class="text-xs text-gray-500">active hypotheses</div>
          <div class="mt-2 text-xs space-y-1">
            <div class="flex justify-between">
              <span class="text-green-600">{{ discoveryMetrics.validated }} validated</span>
              <span class="text-red-600">{{ discoveryMetrics.invalidated }} invalidated</span>
            </div>
            <div :class="discoveryMetrics.velocityChange >= 0 ? 'text-green-600' : 'text-red-600'">
              {{ discoveryMetrics.velocityChange >= 0 ? '+' : '' }}{{ discoveryMetrics.velocityChange }}% this week
            </div>
          </div>
        </div>

        <!-- Customer Discovery -->
        <div class="card p-4">
          <div class="flex items-center gap-2 mb-2">
            <svg class="w-5 h-5 text-purple-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            <h3 class="text-sm font-medium text-gray-500">Customers</h3>
          </div>
          <div class="text-3xl font-bold text-gray-900">{{ customerMetrics.totalArchetypes }}</div>
          <div class="text-xs text-gray-500">archetypes defined</div>
          <div class="mt-2 text-xs space-y-1">
            <div>{{ customerMetrics.totalInterviews }} total interviews</div>
            <div>{{ customerMetrics.activePartners }} active design partners</div>
          </div>
        </div>

        <!-- Decisions -->
        <div class="card p-4">
          <div class="flex items-center gap-2 mb-2">
            <svg class="w-5 h-5 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
            </svg>
            <h3 class="text-sm font-medium text-gray-500">Decisions</h3>
          </div>
          <div class="text-3xl font-bold text-gray-900">{{ decisionMetrics.decided }}</div>
          <div class="text-xs text-gray-500">decisions made</div>
          <div class="mt-2 text-xs space-y-1">
            <div>{{ decisionMetrics.proposed }} pending decision</div>
            <div class="text-green-600">{{ decisionMetrics.evidenceRate }}% evidence-backed</div>
          </div>
        </div>
      </div>

      <!-- Risk Indicators & Recent Activity -->
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- Risk Indicators -->
        <div class="card p-4">
          <div class="flex items-center gap-2 mb-4">
            <svg class="w-5 h-5 text-amber-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <h3 class="text-sm font-medium text-gray-900">Risk Indicators</h3>
          </div>

          <div v-if="riskIndicators.length === 0" class="text-sm text-gray-500 text-center py-4">
            <svg class="w-8 h-8 mx-auto text-green-400 mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            No significant risks detected
          </div>

          <div v-else class="space-y-2">
            <RouterLink
              v-for="(risk, index) in riskIndicators"
              :key="index"
              :to="risk.path"
              :class="[getSeverityClass(risk.severity), 'block p-3 rounded-lg border hover:opacity-80 transition-opacity']"
            >
              <div class="flex items-center justify-between">
                <span class="text-sm font-medium">{{ risk.message }}</span>
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                </svg>
              </div>
            </RouterLink>
          </div>
        </div>

        <!-- Recent Activity -->
        <div class="card p-4">
          <div class="flex items-center gap-2 mb-4">
            <svg class="w-5 h-5 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <h3 class="text-sm font-medium text-gray-900">Recent Activity</h3>
          </div>

          <div v-if="recentActivities.length === 0" class="text-sm text-gray-500 text-center py-4">
            No recent activity
          </div>

          <div v-else class="space-y-3">
            <RouterLink
              v-for="(activity, index) in recentActivities"
              :key="index"
              :to="activity.path"
              class="flex items-start gap-3 hover:bg-gray-50 p-2 rounded-lg transition-colors"
            >
              <div :class="[
                'w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0',
                activity.type === 'validated' ? 'bg-green-100' : '',
                activity.type === 'decided' ? 'bg-blue-100' : '',
                activity.type === 'shipped' ? 'bg-purple-100' : ''
              ]">
                <svg
                  v-if="activity.type === 'validated'"
                  class="w-4 h-4 text-green-600"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
                <svg
                  v-else-if="activity.type === 'decided'"
                  class="w-4 h-4 text-blue-600"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                </svg>
                <svg
                  v-else
                  class="w-4 h-4 text-purple-600"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
                </svg>
              </div>
              <div class="flex-1 min-w-0">
                <p class="text-sm text-gray-900 truncate">{{ activity.title }}</p>
                <p class="text-xs text-gray-500">{{ formatDate(activity.date) }}</p>
              </div>
            </RouterLink>
          </div>
        </div>
      </div>

      <!-- Validation Rate & Evidence Quality -->
      <div class="card p-4">
        <div class="flex items-center gap-2 mb-4">
          <svg class="w-5 h-5 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
          </svg>
          <h3 class="text-sm font-medium text-gray-900">Discovery & Evidence Quality</h3>
        </div>

        <div class="grid grid-cols-2 sm:grid-cols-4 gap-6">
          <div class="text-center">
            <div :class="[getScoreColor(discoveryMetrics.validationRate), 'text-3xl font-bold']">
              {{ discoveryMetrics.validationRate }}%
            </div>
            <div class="text-xs text-gray-500 mt-1">Validation Rate</div>
          </div>
          <div class="text-center">
            <div class="text-3xl font-bold text-indigo-600">{{ discoveryMetrics.withStrongEvidence }}</div>
            <div class="text-xs text-gray-500 mt-1">Strong Evidence</div>
          </div>
          <div class="text-center">
            <div class="text-3xl font-bold text-amber-600">{{ discoveryMetrics.highPriority }}</div>
            <div class="text-xs text-gray-500 mt-1">High Priority</div>
          </div>
          <div class="text-center">
            <div class="text-3xl font-bold text-purple-600">{{ decisionMetrics.autoGenerated }}</div>
            <div class="text-xs text-gray-500 mt-1">Auto-Generated Decisions</div>
          </div>
        </div>
      </div>

      <!-- Quick Navigation -->
      <div class="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <RouterLink to="/focus-areas" class="card p-4 hover:border-indigo-300 transition-colors text-center">
          <div class="text-sm font-medium text-gray-900">Focus Areas</div>
          <div class="text-xs text-gray-500 mt-1">Manage strategic bets</div>
        </RouterLink>
        <RouterLink to="/discovery" class="card p-4 hover:border-green-300 transition-colors text-center">
          <div class="text-sm font-medium text-gray-900">Discovery Hub</div>
          <div class="text-xs text-gray-500 mt-1">Validate hypotheses</div>
        </RouterLink>
        <RouterLink to="/decisions" class="card p-4 hover:border-blue-300 transition-colors text-center">
          <div class="text-sm font-medium text-gray-900">Decisions Log</div>
          <div class="text-xs text-gray-500 mt-1">Review decisions</div>
        </RouterLink>
        <RouterLink to="/objectives" class="card p-4 hover:border-purple-300 transition-colors text-center">
          <div class="text-sm font-medium text-gray-900">Objectives</div>
          <div class="text-xs text-gray-500 mt-1">Track OKRs</div>
        </RouterLink>
      </div>
    </template>
  </div>
</template>
